[package]
name = "error-support"
version = "0.1.1"
authors = ["Thom Chiovoloni <tchiovoloni@mozilla.com>"]
edition = "2018"
license = "MPL-2.0"

[dependencies]

[dependencies.backtrace]
optional = true
version = "0.3"
